/run/initialize

/ang/particle photon 
/ang/energy 3.002 MeV

/ang/nstates 3
/ang/state1 0.
/ang/state2 1.
/ang/state3 0.

/ang/delta12 0.
/ang/delta23 0.

/ang/sourceX 0. mm
/ang/sourceY 0. mm
/ang/sourceZ 0. mm

/ang/sourceDX 20. mm #Full length of the box
/ang/sourceDY 20. mm
/ang/sourceDZ 10. mm

/ang/sourcePV Nd150_Target
#/ang/sourcePV Sm152_Target_Physical

/run/printProgress 100000
/run/beamOn 300
